<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-03 03:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
=======
# Generated by Django 5.1.2 on 2024-11-03 04:54

>>>>>>> origin/Nastya
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/Nastya
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок темы')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.CharField(max_length=200, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
>>>>>>> origin/Nastya
            ],
        ),
    ]
